package models

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

type Tool struct {
	Definition mcp.Tool
	Handler    func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error)
}

// ScoringDetail represents the ScoringDetail schema from the OpenAPI specification
type ScoringDetail struct {
	Scoringtype string `json:"ScoringType,omitempty"`
	Season int `json:"Season,omitempty"`
	Team string `json:"Team,omitempty"`
	Gamekey string `json:"GameKey,omitempty"`
	Scoreid int `json:"ScoreID,omitempty"`
	Scoringplayid int `json:"ScoringPlayID,omitempty"`
	Seasontype int `json:"SeasonType,omitempty"`
	Length int `json:"Length,omitempty"`
	Playergameid int `json:"PlayerGameID,omitempty"`
	Scoringdetailid int `json:"ScoringDetailID,omitempty"`
	Week int `json:"Week,omitempty"`
	Playerid int `json:"PlayerID,omitempty"`
}

// FantasyDefenseSeasonProjection represents the FantasyDefenseSeasonProjection schema from the OpenAPI specification
type FantasyDefenseSeasonProjection struct {
	Fourthdownconversions float64 `json:"FourthDownConversions,omitempty"`
	Interceptionreturnyards float64 `json:"InterceptionReturnYards,omitempty"`
	Draftkingsquarterbackfantasypointsallowed float64 `json:"DraftKingsQuarterbackFantasyPointsAllowed,omitempty"`
	Blockedkicks float64 `json:"BlockedKicks,omitempty"`
	Quarterbackhits float64 `json:"QuarterbackHits,omitempty"`
	Pointsallowed float64 `json:"PointsAllowed,omitempty"`
	Fantasydraftkickerfantasypointsallowed float64 `json:"FantasyDraftKickerFantasyPointsAllowed,omitempty"`
	Puntreturntouchdowns float64 `json:"PuntReturnTouchdowns,omitempty"`
	Yahootightendfantasypointsallowed float64 `json:"YahooTightEndFantasyPointsAllowed,omitempty"`
	Fantasypoints float64 `json:"FantasyPoints,omitempty"`
	Fanduelquarterbackfantasypointsallowed float64 `json:"FanDuelQuarterbackFantasyPointsAllowed,omitempty"`
	Kickerfantasypointsallowed float64 `json:"KickerFantasyPointsAllowed,omitempty"`
	Fanduelfantasypointsallowed float64 `json:"FanDuelFantasyPointsAllowed,omitempty"`
	Kickreturnlong float64 `json:"KickReturnLong,omitempty"`
	Fourthdownattempts float64 `json:"FourthDownAttempts,omitempty"`
	Fantasydraftquarterbackfantasypointsallowed float64 `json:"FantasyDraftQuarterbackFantasyPointsAllowed,omitempty"`
	Offensiveyardsallowed float64 `json:"OffensiveYardsAllowed,omitempty"`
	Fieldgoalreturntouchdowns float64 `json:"FieldGoalReturnTouchdowns,omitempty"`
	Kickreturns float64 `json:"KickReturns,omitempty"`
	Sackyards float64 `json:"SackYards,omitempty"`
	Teamid int `json:"TeamID,omitempty"`
	Defensivetouchdowns float64 `json:"DefensiveTouchdowns,omitempty"`
	Blockedkickreturntouchdowns float64 `json:"BlockedKickReturnTouchdowns,omitempty"`
	Scoringdetails []ScoringDetail `json:"ScoringDetails,omitempty"`
	Puntreturnlong float64 `json:"PuntReturnLong,omitempty"`
	Team string `json:"Team,omitempty"`
	Averagedraftpositionppr float64 `json:"AverageDraftPositionPPR,omitempty"`
	Thirddownconversions float64 `json:"ThirdDownConversions,omitempty"`
	Fantasypointsfantasydraft float64 `json:"FantasyPointsFantasyDraft,omitempty"`
	Fumblereturntouchdowns float64 `json:"FumbleReturnTouchdowns,omitempty"`
	Kickreturnyards float64 `json:"KickReturnYards,omitempty"`
	Tacklesforloss float64 `json:"TacklesForLoss,omitempty"`
	Averagedraftposition2qb float64 `json:"AverageDraftPosition2QB,omitempty"`
	Fumblesrecovered float64 `json:"FumblesRecovered,omitempty"`
	Twopointconversionreturns float64 `json:"TwoPointConversionReturns,omitempty"`
	Auctionvalue float64 `json:"AuctionValue,omitempty"`
	Runningbackfantasypointsallowed float64 `json:"RunningbackFantasyPointsAllowed,omitempty"`
	Puntreturns float64 `json:"PuntReturns,omitempty"`
	Temperature int `json:"Temperature,omitempty"`
	Yahoofantasypointsallowed float64 `json:"YahooFantasyPointsAllowed,omitempty"`
	Averagedraftpositiondynasty float64 `json:"AverageDraftPositionDynasty,omitempty"`
	Globalteamid int `json:"GlobalTeamID,omitempty"`
	Quarterbackfantasypointsallowed float64 `json:"QuarterbackFantasyPointsAllowed,omitempty"`
	Fieldgoalreturnyards float64 `json:"FieldGoalReturnYards,omitempty"`
	Fantasydraftwidereceiverfantasypointsallowed float64 `json:"FantasyDraftWideReceiverFantasyPointsAllowed,omitempty"`
	Draftkingsfantasypointsallowed float64 `json:"DraftKingsFantasyPointsAllowed,omitempty"`
	Blockedkickreturnyards float64 `json:"BlockedKickReturnYards,omitempty"`
	Interceptionreturntouchdowns float64 `json:"InterceptionReturnTouchdowns,omitempty"`
	Fantasydraftrunningbackfantasypointsallowed float64 `json:"FantasyDraftRunningbackFantasyPointsAllowed,omitempty"`
	Fanduelkickerfantasypointsallowed float64 `json:"FanDuelKickerFantasyPointsAllowed,omitempty"`
	Season int `json:"Season,omitempty"`
	Draftkingsrunningbackfantasypointsallowed float64 `json:"DraftKingsRunningbackFantasyPointsAllowed,omitempty"`
	Yahoowidereceiverfantasypointsallowed float64 `json:"YahooWideReceiverFantasyPointsAllowed,omitempty"`
	Fantasypointsallowed float64 `json:"FantasyPointsAllowed,omitempty"`
	Fanduelwidereceiverfantasypointsallowed float64 `json:"FanDuelWideReceiverFantasyPointsAllowed,omitempty"`
	Draftkingswidereceiverfantasypointsallowed float64 `json:"DraftKingsWideReceiverFantasyPointsAllowed,omitempty"`
	Fantasydraftfantasypointsallowed float64 `json:"FantasyDraftFantasyPointsAllowed,omitempty"`
	Draftkingskickerfantasypointsallowed float64 `json:"DraftKingsKickerFantasyPointsAllowed,omitempty"`
	Tightendfantasypointsallowed float64 `json:"TightEndFantasyPointsAllowed,omitempty"`
	Interceptions float64 `json:"Interceptions,omitempty"`
	Pointsallowedbydefensespecialteams float64 `json:"PointsAllowedByDefenseSpecialTeams,omitempty"`
	Humidity int `json:"Humidity,omitempty"`
	Kickreturntouchdowns float64 `json:"KickReturnTouchdowns,omitempty"`
	Games int `json:"Games,omitempty"`
	Fumblereturnyards float64 `json:"FumbleReturnYards,omitempty"`
	Yahooquarterbackfantasypointsallowed float64 `json:"YahooQuarterbackFantasyPointsAllowed,omitempty"`
	Thirddownattempts float64 `json:"ThirdDownAttempts,omitempty"`
	Sacks float64 `json:"Sacks,omitempty"`
	Auctionvalueppr float64 `json:"AuctionValuePPR,omitempty"`
	Assistedtackles float64 `json:"AssistedTackles,omitempty"`
	Solotackles float64 `json:"SoloTackles,omitempty"`
	Seasontype int `json:"SeasonType,omitempty"`
	Fantasypointsfanduel float64 `json:"FantasyPointsFanDuel,omitempty"`
	Yahoorunningbackfantasypointsallowed float64 `json:"YahooRunningbackFantasyPointsAllowed,omitempty"`
	Fantasypointsdraftkings float64 `json:"FantasyPointsDraftKings,omitempty"`
	Fumblesforced float64 `json:"FumblesForced,omitempty"`
	Safeties float64 `json:"Safeties,omitempty"`
	Playerid int `json:"PlayerID,omitempty"`
	Widereceiverfantasypointsallowed float64 `json:"WideReceiverFantasyPointsAllowed,omitempty"`
	Puntreturnyards float64 `json:"PuntReturnYards,omitempty"`
	Specialteamstouchdowns float64 `json:"SpecialTeamsTouchdowns,omitempty"`
	Touchdownsscored float64 `json:"TouchdownsScored,omitempty"`
	Fantasydrafttightendfantasypointsallowed float64 `json:"FantasyDraftTightEndFantasyPointsAllowed,omitempty"`
	Fanduelrunningbackfantasypointsallowed float64 `json:"FanDuelRunningbackFantasyPointsAllowed,omitempty"`
	Windspeed int `json:"WindSpeed,omitempty"`
	Fantasypointsyahoo float64 `json:"FantasyPointsYahoo,omitempty"`
	Draftkingstightendfantasypointsallowed float64 `json:"DraftKingsTightEndFantasyPointsAllowed,omitempty"`
	Averagedraftposition float64 `json:"AverageDraftPosition,omitempty"`
	Fandueltightendfantasypointsallowed float64 `json:"FanDuelTightEndFantasyPointsAllowed,omitempty"`
	Passesdefended float64 `json:"PassesDefended,omitempty"`
	Yahookickerfantasypointsallowed float64 `json:"YahooKickerFantasyPointsAllowed,omitempty"`
}

// DfsSlate represents the DfsSlate schema from the OpenAPI specification
type DfsSlate struct {
	Ismultidayslate bool `json:"IsMultiDaySlate,omitempty"`
	Operatorday string `json:"OperatorDay,omitempty"`
	Removedbyoperator bool `json:"RemovedByOperator,omitempty"`
	Salarycap int `json:"SalaryCap,omitempty"`
	Dfsslategames []DfsSlateGame `json:"DfsSlateGames,omitempty"`
	Dfsslateplayers []DfsSlatePlayer `json:"DfsSlatePlayers,omitempty"`
	Operatorgametype string `json:"OperatorGameType,omitempty"`
	Operatorstarttime string `json:"OperatorStartTime,omitempty"`
	Slaterosterslots []string `json:"SlateRosterSlots,omitempty"`
	Operatorname string `json:"OperatorName,omitempty"`
	Operatorslateid int `json:"OperatorSlateID,omitempty"`
	Slateid int `json:"SlateID,omitempty"`
	Numberofgames int `json:"NumberOfGames,omitempty"`
	Operator string `json:"Operator,omitempty"`
}

// DfsSlatePlayerOwnershipProjection represents the DfsSlatePlayerOwnershipProjection schema from the OpenAPI specification
type DfsSlatePlayerOwnershipProjection struct {
	Slateid int `json:"SlateID,omitempty"`
	Fantasydefenseplayerid int `json:"FantasyDefensePlayerID,omitempty"`
	Iscaptain bool `json:"IsCaptain,omitempty"`
	Playerid int `json:"PlayerID,omitempty"`
	Projectedownershippercentage float64 `json:"ProjectedOwnershipPercentage,omitempty"`
}

// FantasyDefenseGameProjection represents the FantasyDefenseGameProjection schema from the OpenAPI specification
type FantasyDefenseGameProjection struct {
	Tacklesforloss float64 `json:"TacklesForLoss,omitempty"`
	Victivsalary int `json:"VictivSalary,omitempty"`
	Safeties float64 `json:"Safeties,omitempty"`
	Fanduelquarterbackfantasypointsallowed float64 `json:"FanDuelQuarterbackFantasyPointsAllowed,omitempty"`
	Team string `json:"Team,omitempty"`
	Yahookickerfantasypointsallowed float64 `json:"YahooKickerFantasyPointsAllowed,omitempty"`
	Stadium string `json:"Stadium,omitempty"`
	Datetime string `json:"DateTime,omitempty"`
	Scoringdetails []ScoringDetail `json:"ScoringDetails,omitempty"`
	Draftkingskickerfantasypointsallowed float64 `json:"DraftKingsKickerFantasyPointsAllowed,omitempty"`
	Fanduelkickerfantasypointsallowed float64 `json:"FanDuelKickerFantasyPointsAllowed,omitempty"`
	Fantasydraftposition string `json:"FantasyDraftPosition,omitempty"`
	Draftkingsposition string `json:"DraftKingsPosition,omitempty"`
	Pointsallowed float64 `json:"PointsAllowed,omitempty"`
	Fantasypointsyahoo float64 `json:"FantasyPointsYahoo,omitempty"`
	Kickreturns float64 `json:"KickReturns,omitempty"`
	Kickreturnyards float64 `json:"KickReturnYards,omitempty"`
	Puntreturnlong float64 `json:"PuntReturnLong,omitempty"`
	Thirddownconversions float64 `json:"ThirdDownConversions,omitempty"`
	Touchdownsscored float64 `json:"TouchdownsScored,omitempty"`
	Draftkingsquarterbackfantasypointsallowed float64 `json:"DraftKingsQuarterbackFantasyPointsAllowed,omitempty"`
	Assistedtackles float64 `json:"AssistedTackles,omitempty"`
	Kickreturntouchdowns float64 `json:"KickReturnTouchdowns,omitempty"`
	Windspeed int `json:"WindSpeed,omitempty"`
	Passesdefended float64 `json:"PassesDefended,omitempty"`
	Teamid int `json:"TeamID,omitempty"`
	Kickerfantasypointsallowed float64 `json:"KickerFantasyPointsAllowed,omitempty"`
	Puntreturnyards float64 `json:"PuntReturnYards,omitempty"`
	Seasontype int `json:"SeasonType,omitempty"`
	Fantasypoints float64 `json:"FantasyPoints,omitempty"`
	Fantasypointsfanduel float64 `json:"FantasyPointsFanDuel,omitempty"`
	Blockedkickreturntouchdowns float64 `json:"BlockedKickReturnTouchdowns,omitempty"`
	Season int `json:"Season,omitempty"`
	Twopointconversionreturns float64 `json:"TwoPointConversionReturns,omitempty"`
	Fantasydraftrunningbackfantasypointsallowed float64 `json:"FantasyDraftRunningbackFantasyPointsAllowed,omitempty"`
	Interceptions float64 `json:"Interceptions,omitempty"`
	Defensivetouchdowns float64 `json:"DefensiveTouchdowns,omitempty"`
	Fantasydraftfantasypointsallowed float64 `json:"FantasyDraftFantasyPointsAllowed,omitempty"`
	Draftkingsrunningbackfantasypointsallowed float64 `json:"DraftKingsRunningbackFantasyPointsAllowed,omitempty"`
	Fumblereturnyards float64 `json:"FumbleReturnYards,omitempty"`
	Globalgameid int `json:"GlobalGameID,omitempty"`
	Fanduelwidereceiverfantasypointsallowed float64 `json:"FanDuelWideReceiverFantasyPointsAllowed,omitempty"`
	Opponentid int `json:"OpponentID,omitempty"`
	Runningbackfantasypointsallowed float64 `json:"RunningbackFantasyPointsAllowed,omitempty"`
	Yahoowidereceiverfantasypointsallowed float64 `json:"YahooWideReceiverFantasyPointsAllowed,omitempty"`
	Fantasydraftkickerfantasypointsallowed float64 `json:"FantasyDraftKickerFantasyPointsAllowed,omitempty"`
	Widereceiverfantasypointsallowed float64 `json:"WideReceiverFantasyPointsAllowed,omitempty"`
	Fanduelsalary int `json:"FanDuelSalary,omitempty"`
	Opponent string `json:"Opponent,omitempty"`
	Pointsallowedbydefensespecialteams float64 `json:"PointsAllowedByDefenseSpecialTeams,omitempty"`
	Globalopponentid int `json:"GlobalOpponentID,omitempty"`
	Yahooquarterbackfantasypointsallowed float64 `json:"YahooQuarterbackFantasyPointsAllowed,omitempty"`
	Interceptionreturnyards float64 `json:"InterceptionReturnYards,omitempty"`
	Draftkingsfantasypointsallowed float64 `json:"DraftKingsFantasyPointsAllowed,omitempty"`
	Specialteamstouchdowns float64 `json:"SpecialTeamsTouchdowns,omitempty"`
	Fieldgoalreturntouchdowns float64 `json:"FieldGoalReturnTouchdowns,omitempty"`
	Temperature int `json:"Temperature,omitempty"`
	Fantasydraftquarterbackfantasypointsallowed float64 `json:"FantasyDraftQuarterbackFantasyPointsAllowed,omitempty"`
	Fumblesrecovered float64 `json:"FumblesRecovered,omitempty"`
	Fanduelrunningbackfantasypointsallowed float64 `json:"FanDuelRunningbackFantasyPointsAllowed,omitempty"`
	Humidity int `json:"Humidity,omitempty"`
	Tightendfantasypointsallowed float64 `json:"TightEndFantasyPointsAllowed,omitempty"`
	Yahootightendfantasypointsallowed float64 `json:"YahooTightEndFantasyPointsAllowed,omitempty"`
	Solotackles float64 `json:"SoloTackles,omitempty"`
	Yahoorunningbackfantasypointsallowed float64 `json:"YahooRunningbackFantasyPointsAllowed,omitempty"`
	Fanduelfantasypointsallowed float64 `json:"FanDuelFantasyPointsAllowed,omitempty"`
	Fantasydraftwidereceiverfantasypointsallowed float64 `json:"FantasyDraftWideReceiverFantasyPointsAllowed,omitempty"`
	Homeoraway string `json:"HomeOrAway,omitempty"`
	Fantasydrafttightendfantasypointsallowed float64 `json:"FantasyDraftTightEndFantasyPointsAllowed,omitempty"`
	Fanduelposition string `json:"FanDuelPosition,omitempty"`
	Fumblesforced float64 `json:"FumblesForced,omitempty"`
	Isgameover bool `json:"IsGameOver,omitempty"`
	Opponentpositionrank int `json:"OpponentPositionRank,omitempty"`
	Puntreturns float64 `json:"PuntReturns,omitempty"`
	Draftkingssalary int `json:"DraftKingsSalary,omitempty"`
	Week int `json:"Week,omitempty"`
	Date string `json:"Date,omitempty"`
	Blockedkickreturnyards float64 `json:"BlockedKickReturnYards,omitempty"`
	Fantasypointsdraftkings float64 `json:"FantasyPointsDraftKings,omitempty"`
	Draftkingswidereceiverfantasypointsallowed float64 `json:"DraftKingsWideReceiverFantasyPointsAllowed,omitempty"`
	Kickreturnlong float64 `json:"KickReturnLong,omitempty"`
	Playerid int `json:"PlayerID,omitempty"`
	Quarterbackfantasypointsallowed float64 `json:"QuarterbackFantasyPointsAllowed,omitempty"`
	Scoreid int `json:"ScoreID,omitempty"`
	Fantasydatasalary int `json:"FantasyDataSalary,omitempty"`
	Sacks float64 `json:"Sacks,omitempty"`
	Interceptionreturntouchdowns float64 `json:"InterceptionReturnTouchdowns,omitempty"`
	Fantasydraftsalary int `json:"FantasyDraftSalary,omitempty"`
	Fandueltightendfantasypointsallowed float64 `json:"FanDuelTightEndFantasyPointsAllowed,omitempty"`
	Gamekey string `json:"GameKey,omitempty"`
	Draftkingstightendfantasypointsallowed float64 `json:"DraftKingsTightEndFantasyPointsAllowed,omitempty"`
	Fumblereturntouchdowns float64 `json:"FumbleReturnTouchdowns,omitempty"`
	Fantasypointsfantasydraft float64 `json:"FantasyPointsFantasyDraft,omitempty"`
	Offensiveyardsallowed float64 `json:"OffensiveYardsAllowed,omitempty"`
	Fieldgoalreturnyards float64 `json:"FieldGoalReturnYards,omitempty"`
	Day string `json:"Day,omitempty"`
	Fantasydefenseid int `json:"FantasyDefenseID,omitempty"`
	Yahoofantasypointsallowed float64 `json:"YahooFantasyPointsAllowed,omitempty"`
	Blockedkicks float64 `json:"BlockedKicks,omitempty"`
	Fantasypointsallowed float64 `json:"FantasyPointsAllowed,omitempty"`
	Opponentrank int `json:"OpponentRank,omitempty"`
	Yahoosalary int `json:"YahooSalary,omitempty"`
	Thirddownattempts float64 `json:"ThirdDownAttempts,omitempty"`
	Fourthdownconversions float64 `json:"FourthDownConversions,omitempty"`
	Yahooposition string `json:"YahooPosition,omitempty"`
	Puntreturntouchdowns float64 `json:"PuntReturnTouchdowns,omitempty"`
	Fourthdownattempts float64 `json:"FourthDownAttempts,omitempty"`
	Globalteamid int `json:"GlobalTeamID,omitempty"`
	Sackyards float64 `json:"SackYards,omitempty"`
	Quarterbackhits float64 `json:"QuarterbackHits,omitempty"`
}

// DfsSlateGame represents the DfsSlateGame schema from the OpenAPI specification
type DfsSlateGame struct {
	Removedbyoperator bool `json:"RemovedByOperator,omitempty"`
	Scoreid int `json:"ScoreID,omitempty"`
	Slategameid int `json:"SlateGameID,omitempty"`
	Slateid int `json:"SlateID,omitempty"`
	Game Schedule `json:"Game,omitempty"`
	Gameid int `json:"GameID,omitempty"`
	Operatorgameid int `json:"OperatorGameID,omitempty"`
}

// DfsSlateWithOwnershipProjection represents the DfsSlateWithOwnershipProjection schema from the OpenAPI specification
type DfsSlateWithOwnershipProjection struct {
	Slateid int `json:"SlateID,omitempty"`
	Slateownershipprojections []DfsSlatePlayerOwnershipProjection `json:"SlateOwnershipProjections,omitempty"`
	Operator string `json:"Operator,omitempty"`
	Operatorday string `json:"OperatorDay,omitempty"`
	Operatorname string `json:"OperatorName,omitempty"`
	Operatorslateid int `json:"OperatorSlateID,omitempty"`
	Operatorstarttime string `json:"OperatorStartTime,omitempty"`
}

// PlayerSeasonProjection represents the PlayerSeasonProjection schema from the OpenAPI specification
type PlayerSeasonProjection struct {
	Specialteamssolotackles float64 `json:"SpecialTeamsSoloTackles,omitempty"`
	Passingcompletionpercentage float64 `json:"PassingCompletionPercentage,omitempty"`
	Safetiesallowed float64 `json:"SafetiesAllowed,omitempty"`
	Fantasyposition string `json:"FantasyPosition,omitempty"`
	Auctionvalueppr float64 `json:"AuctionValuePPR,omitempty"`
	Offensivetouchdowns float64 `json:"OffensiveTouchdowns,omitempty"`
	Defensivetouchdowns float64 `json:"DefensiveTouchdowns,omitempty"`
	Playerid int `json:"PlayerID,omitempty"`
	Puntreturnyards float64 `json:"PuntReturnYards,omitempty"`
	Fieldgoalsmade50plus float64 `json:"FieldGoalsMade50Plus,omitempty"`
	Passingsacks float64 `json:"PassingSacks,omitempty"`
	Specialteamsfumblesrecovered float64 `json:"SpecialTeamsFumblesRecovered,omitempty"`
	Fantasypoints float64 `json:"FantasyPoints,omitempty"`
	Puntreturnyardsperattempt float64 `json:"PuntReturnYardsPerAttempt,omitempty"`
	Started int `json:"Started,omitempty"`
	Passinglong float64 `json:"PassingLong,omitempty"`
	Defensiveteamsnaps int `json:"DefensiveTeamSnaps,omitempty"`
	Punts float64 `json:"Punts,omitempty"`
	Receivinglong float64 `json:"ReceivingLong,omitempty"`
	Interceptionreturntouchdowns float64 `json:"InterceptionReturnTouchdowns,omitempty"`
	Puntreturns float64 `json:"PuntReturns,omitempty"`
	Fumblereturnyards float64 `json:"FumbleReturnYards,omitempty"`
	Tacklesforloss float64 `json:"TacklesForLoss,omitempty"`
	Rushinglong float64 `json:"RushingLong,omitempty"`
	Passingattempts float64 `json:"PassingAttempts,omitempty"`
	Offensiveteamsnaps int `json:"OffensiveTeamSnaps,omitempty"`
	Twopointconversionreceptions float64 `json:"TwoPointConversionReceptions,omitempty"`
	Fieldgoalsattempted float64 `json:"FieldGoalsAttempted,omitempty"`
	Fieldgoalsmade0to19 float64 `json:"FieldGoalsMade0to19,omitempty"`
	Blockedkicks float64 `json:"BlockedKicks,omitempty"`
	Auctionvalue float64 `json:"AuctionValue,omitempty"`
	Playerseasonid int `json:"PlayerSeasonID,omitempty"`
	Solotackles float64 `json:"SoloTackles,omitempty"`
	Kickreturnyardsperattempt float64 `json:"KickReturnYardsPerAttempt,omitempty"`
	Puntyards float64 `json:"PuntYards,omitempty"`
	Blockedkickreturnyards float64 `json:"BlockedKickReturnYards,omitempty"`
	Passingyards float64 `json:"PassingYards,omitempty"`
	Fieldgoalslongestmade float64 `json:"FieldGoalsLongestMade,omitempty"`
	Temperature int `json:"Temperature,omitempty"`
	Interceptionreturnyards float64 `json:"InterceptionReturnYards,omitempty"`
	Passinginterceptions float64 `json:"PassingInterceptions,omitempty"`
	Shortname string `json:"ShortName,omitempty"`
	Averagedraftpositionppr float64 `json:"AverageDraftPositionPPR,omitempty"`
	Fieldgoalreturnyards float64 `json:"FieldGoalReturnYards,omitempty"`
	Fieldgoalpercentage float64 `json:"FieldGoalPercentage,omitempty"`
	Passingyardsperattempt float64 `json:"PassingYardsPerAttempt,omitempty"`
	Receivingyardsperreception float64 `json:"ReceivingYardsPerReception,omitempty"`
	Miscfumblesforced float64 `json:"MiscFumblesForced,omitempty"`
	Miscassistedtackles float64 `json:"MiscAssistedTackles,omitempty"`
	Puntreturntouchdowns float64 `json:"PuntReturnTouchdowns,omitempty"`
	Puntshadblocked float64 `json:"PuntsHadBlocked,omitempty"`
	Kickreturnfaircatches float64 `json:"KickReturnFairCatches,omitempty"`
	Passingsackyards float64 `json:"PassingSackYards,omitempty"`
	Averagedraftpositiondynasty float64 `json:"AverageDraftPositionDynasty,omitempty"`
	Extrapointsattempted float64 `json:"ExtraPointsAttempted,omitempty"`
	Extrapointshadblocked float64 `json:"ExtraPointsHadBlocked,omitempty"`
	Puntnetyards float64 `json:"PuntNetYards,omitempty"`
	Kickreturns float64 `json:"KickReturns,omitempty"`
	Fantasypointsdraftkings float64 `json:"FantasyPointsDraftKings,omitempty"`
	Miscsolotackles float64 `json:"MiscSoloTackles,omitempty"`
	Played int `json:"Played,omitempty"`
	Offensivesnapsplayed int `json:"OffensiveSnapsPlayed,omitempty"`
	Touchdowns float64 `json:"Touchdowns,omitempty"`
	Kickreturnyards float64 `json:"KickReturnYards,omitempty"`
	Fantasypointsyahoo float64 `json:"FantasyPointsYahoo,omitempty"`
	Globalteamid int `json:"GlobalTeamID,omitempty"`
	Kickreturnlong float64 `json:"KickReturnLong,omitempty"`
	Teamid int `json:"TeamID,omitempty"`
	Fumblesforced float64 `json:"FumblesForced,omitempty"`
	Passingyardspercompletion float64 `json:"PassingYardsPerCompletion,omitempty"`
	Punttouchbacks float64 `json:"PuntTouchbacks,omitempty"`
	Defensivesnapsplayed int `json:"DefensiveSnapsPlayed,omitempty"`
	Rushingattempts float64 `json:"RushingAttempts,omitempty"`
	Sackyards float64 `json:"SackYards,omitempty"`
	Puntreturnlong float64 `json:"PuntReturnLong,omitempty"`
	Number int `json:"Number,omitempty"`
	Fantasypointsfanduel float64 `json:"FantasyPointsFanDuel,omitempty"`
	Fieldgoalreturntouchdowns float64 `json:"FieldGoalReturnTouchdowns,omitempty"`
	Puntinside20 float64 `json:"PuntInside20,omitempty"`
	Season int `json:"Season,omitempty"`
	Passingrating float64 `json:"PassingRating,omitempty"`
	Receivingtargets float64 `json:"ReceivingTargets,omitempty"`
	Team string `json:"Team,omitempty"`
	Twopointconversionruns float64 `json:"TwoPointConversionRuns,omitempty"`
	Puntreturnfaircatches float64 `json:"PuntReturnFairCatches,omitempty"`
	Twopointconversionreturns float64 `json:"TwoPointConversionReturns,omitempty"`
	Rushingyards float64 `json:"RushingYards,omitempty"`
	Sacks float64 `json:"Sacks,omitempty"`
	Averagedraftposition2qb float64 `json:"AverageDraftPosition2QB,omitempty"`
	Averagedraftposition float64 `json:"AverageDraftPosition,omitempty"`
	Fumblereturntouchdowns float64 `json:"FumbleReturnTouchdowns,omitempty"`
	Receptionpercentage float64 `json:"ReceptionPercentage,omitempty"`
	Specialteamsteamsnaps int `json:"SpecialTeamsTeamSnaps,omitempty"`
	Quarterbackhits float64 `json:"QuarterbackHits,omitempty"`
	Assistedtackles float64 `json:"AssistedTackles,omitempty"`
	Windspeed int `json:"WindSpeed,omitempty"`
	Fantasypointsfantasydraft float64 `json:"FantasyPointsFantasyDraft,omitempty"`
	Passingtouchdowns float64 `json:"PassingTouchdowns,omitempty"`
	Fieldgoalsmade30to39 float64 `json:"FieldGoalsMade30to39,omitempty"`
	Position string `json:"Position,omitempty"`
	Passingcompletions float64 `json:"PassingCompletions,omitempty"`
	Seasontype int `json:"SeasonType,omitempty"`
	Interceptions float64 `json:"Interceptions,omitempty"`
	Safeties float64 `json:"Safeties,omitempty"`
	Specialteamsfumblesforced float64 `json:"SpecialTeamsFumblesForced,omitempty"`
	Receivingyardspertarget float64 `json:"ReceivingYardsPerTarget,omitempty"`
	Fieldgoalsmade40to49 float64 `json:"FieldGoalsMade40to49,omitempty"`
	Receivingyards float64 `json:"ReceivingYards,omitempty"`
	Activated int `json:"Activated,omitempty"`
	Puntaverage float64 `json:"PuntAverage,omitempty"`
	Specialteamsassistedtackles float64 `json:"SpecialTeamsAssistedTackles,omitempty"`
	Humidity int `json:"Humidity,omitempty"`
	Fumblesrecovered float64 `json:"FumblesRecovered,omitempty"`
	Fumbles float64 `json:"Fumbles,omitempty"`
	Scoringdetails []ScoringDetail `json:"ScoringDetails,omitempty"`
	Fumblesownrecoveries float64 `json:"FumblesOwnRecoveries,omitempty"`
	Fantasypointsppr float64 `json:"FantasyPointsPPR,omitempty"`
	Tackles float64 `json:"Tackles,omitempty"`
	Fieldgoalshadblocked float64 `json:"FieldGoalsHadBlocked,omitempty"`
	Puntlong float64 `json:"PuntLong,omitempty"`
	Receptions float64 `json:"Receptions,omitempty"`
	Specialteamssnapsplayed int `json:"SpecialTeamsSnapsPlayed,omitempty"`
	Offensivefumblerecoverytouchdowns int `json:"OffensiveFumbleRecoveryTouchdowns,omitempty"`
	Name string `json:"Name,omitempty"`
	Rushingtouchdowns float64 `json:"RushingTouchdowns,omitempty"`
	Miscfumblesrecovered float64 `json:"MiscFumblesRecovered,omitempty"`
	Fieldgoalsmade20to29 float64 `json:"FieldGoalsMade20to29,omitempty"`
	Fumblesoutofbounds float64 `json:"FumblesOutOfBounds,omitempty"`
	Fieldgoalsmade float64 `json:"FieldGoalsMade,omitempty"`
	Passesdefended float64 `json:"PassesDefended,omitempty"`
	Blockedkickreturntouchdowns float64 `json:"BlockedKickReturnTouchdowns,omitempty"`
	Kickreturntouchdowns float64 `json:"KickReturnTouchdowns,omitempty"`
	Specialteamstouchdowns float64 `json:"SpecialTeamsTouchdowns,omitempty"`
	Extrapointsmade float64 `json:"ExtraPointsMade,omitempty"`
	Rushingyardsperattempt float64 `json:"RushingYardsPerAttempt,omitempty"`
	Twopointconversionpasses float64 `json:"TwoPointConversionPasses,omitempty"`
	Receivingtouchdowns float64 `json:"ReceivingTouchdowns,omitempty"`
	Puntnetaverage float64 `json:"PuntNetAverage,omitempty"`
	Fumbleslost float64 `json:"FumblesLost,omitempty"`
	Averagedraftpositionrookie float64 `json:"AverageDraftPositionRookie,omitempty"`
	Positioncategory string `json:"PositionCategory,omitempty"`
}

// Schedule represents the Schedule schema from the OpenAPI specification
type Schedule struct {
	Week int `json:"Week,omitempty"`
	Forecastwindchill int `json:"ForecastWindChill,omitempty"`
	Awayteam string `json:"AwayTeam,omitempty"`
	Forecasttemplow int `json:"ForecastTempLow,omitempty"`
	Globalhometeamid int `json:"GlobalHomeTeamID,omitempty"`
	Hometeam string `json:"HomeTeam,omitempty"`
	Overunder float64 `json:"OverUnder,omitempty"`
	Channel string `json:"Channel,omitempty"`
	Hometeammoneyline int `json:"HomeTeamMoneyLine,omitempty"`
	Globalgameid int `json:"GlobalGameID,omitempty"`
	Awayteammoneyline int `json:"AwayTeamMoneyLine,omitempty"`
	Gamekey string `json:"GameKey,omitempty"`
	Scoreid int `json:"ScoreID,omitempty"`
	Day string `json:"Day,omitempty"`
	Canceled bool `json:"Canceled,omitempty"`
	Forecastwindspeed int `json:"ForecastWindSpeed,omitempty"`
	Stadiumdetails Stadium `json:"StadiumDetails,omitempty"`
	Geolat float64 `json:"GeoLat,omitempty"`
	Geolong float64 `json:"GeoLong,omitempty"`
	Status string `json:"Status,omitempty"`
	Seasontype int `json:"SeasonType,omitempty"`
	Forecasttemphigh int `json:"ForecastTempHigh,omitempty"`
	Date string `json:"Date,omitempty"`
	Datetime string `json:"DateTime,omitempty"`
	Season int `json:"Season,omitempty"`
	Stadiumid int `json:"StadiumID,omitempty"`
	Forecastdescription string `json:"ForecastDescription,omitempty"`
	Globalawayteamid int `json:"GlobalAwayTeamID,omitempty"`
	Pointspread float64 `json:"PointSpread,omitempty"`
}

// Stadium represents the Stadium schema from the OpenAPI specification
type Stadium struct {
	State string `json:"State,omitempty"`
	City string `json:"City,omitempty"`
	Geolong float64 `json:"GeoLong,omitempty"`
	Name string `json:"Name,omitempty"`
	Capacity int `json:"Capacity,omitempty"`
	Country string `json:"Country,omitempty"`
	Geolat float64 `json:"GeoLat,omitempty"`
	TypeField string `json:"Type,omitempty"`
	Stadiumid int `json:"StadiumID,omitempty"`
	Playingsurface string `json:"PlayingSurface,omitempty"`
}

// DfsSlatePlayer represents the DfsSlatePlayer schema from the OpenAPI specification
type DfsSlatePlayer struct {
	Operatorsalary int `json:"OperatorSalary,omitempty"`
	Playerid int `json:"PlayerID,omitempty"`
	Removedbyoperator bool `json:"RemovedByOperator,omitempty"`
	Slateplayerid int `json:"SlatePlayerID,omitempty"`
	Slateid int `json:"SlateID,omitempty"`
	Fantasydefenseprojectionstatid int `json:"FantasyDefenseProjectionStatID,omitempty"`
	Operatorposition string `json:"OperatorPosition,omitempty"`
	Operatorplayerid string `json:"OperatorPlayerID,omitempty"`
	Slategameid int `json:"SlateGameID,omitempty"`
	Team string `json:"Team,omitempty"`
	Operatorslateplayerid string `json:"OperatorSlatePlayerID,omitempty"`
	Operatorplayername string `json:"OperatorPlayerName,omitempty"`
	Teamid int `json:"TeamID,omitempty"`
	Operatorrosterslots []string `json:"OperatorRosterSlots,omitempty"`
	Playergameprojectionstatid int `json:"PlayerGameProjectionStatID,omitempty"`
}

// Player represents the Player schema from the OpenAPI specification
type Player struct {
	Position string `json:"Position,omitempty"`
	Positioncategory string `json:"PositionCategory,omitempty"`
	Experience int `json:"Experience,omitempty"`
	Statsplayerid int `json:"StatsPlayerID,omitempty"`
	Fantasypositiondepthorder int `json:"FantasyPositionDepthOrder,omitempty"`
	Upcomingfanduelsalary int `json:"UpcomingFanDuelSalary,omitempty"`
	Injurypracticedescription string `json:"InjuryPracticeDescription,omitempty"`
	Upcomingopponentpositionrank int `json:"UpcomingOpponentPositionRank,omitempty"`
	Upcomingsalary int `json:"UpcomingSalary,omitempty"`
	Team string `json:"Team,omitempty"`
	Averagedraftposition float64 `json:"AverageDraftPosition,omitempty"`
	Fantasyposition string `json:"FantasyPosition,omitempty"`
	Heightfeet int `json:"HeightFeet,omitempty"`
	College string `json:"College,omitempty"`
	Name string `json:"Name,omitempty"`
	Isundraftedfreeagent bool `json:"IsUndraftedFreeAgent,omitempty"`
	Heightinches int `json:"HeightInches,omitempty"`
	Usatodayheadshotupdated string `json:"UsaTodayHeadshotUpdated,omitempty"`
	Injurystatus string `json:"InjuryStatus,omitempty"`
	Playerid int `json:"PlayerID,omitempty"`
	Firstname string `json:"FirstName,omitempty"`
	Weight int `json:"Weight,omitempty"`
	Fantasydraftname string `json:"FantasyDraftName,omitempty"`
	Fantasydraftplayerid int `json:"FantasyDraftPlayerID,omitempty"`
	Teamid int `json:"TeamID,omitempty"`
	Usatodayheadshoturl string `json:"UsaTodayHeadshotUrl,omitempty"`
	Depthpositioncategory string `json:"DepthPositionCategory,omitempty"`
	Sportradarplayerid string `json:"SportRadarPlayerID,omitempty"`
	Usatodayheadshotnobackgroundupdated string `json:"UsaTodayHeadshotNoBackgroundUpdated,omitempty"`
	Collegedraftteam string `json:"CollegeDraftTeam,omitempty"`
	Upcomingyahoosalary int `json:"UpcomingYahooSalary,omitempty"`
	Experiencestring string `json:"ExperienceString,omitempty"`
	Fantasyalarmplayerid int `json:"FantasyAlarmPlayerID,omitempty"`
	Upcominggameopponent string `json:"UpcomingGameOpponent,omitempty"`
	Yahooplayerid int `json:"YahooPlayerID,omitempty"`
	Lastname string `json:"LastName,omitempty"`
	Upcomingopponentrank int `json:"UpcomingOpponentRank,omitempty"`
	Usatodayplayerid int `json:"UsaTodayPlayerID,omitempty"`
	Yahooname string `json:"YahooName,omitempty"`
	Draftkingsname string `json:"DraftKingsName,omitempty"`
	Depthposition string `json:"DepthPosition,omitempty"`
	Collegedraftyear int `json:"CollegeDraftYear,omitempty"`
	Status string `json:"Status,omitempty"`
	Depthdisplayorder int `json:"DepthDisplayOrder,omitempty"`
	Injurynotes string `json:"InjuryNotes,omitempty"`
	Photourl string `json:"PhotoUrl,omitempty"`
	Injurybodypart string `json:"InjuryBodyPart,omitempty"`
	Upcomingdraftkingssalary int `json:"UpcomingDraftKingsSalary,omitempty"`
	Collegedraftpick int `json:"CollegeDraftPick,omitempty"`
	Height string `json:"Height,omitempty"`
	Birthdate string `json:"BirthDate,omitempty"`
	Collegedraftround int `json:"CollegeDraftRound,omitempty"`
	Rotoworldplayerid int `json:"RotoworldPlayerID,omitempty"`
	Globalteamid int `json:"GlobalTeamID,omitempty"`
	Age int `json:"Age,omitempty"`
	Fanduelplayerid int `json:"FanDuelPlayerID,omitempty"`
	Currentstatus string `json:"CurrentStatus,omitempty"`
	Rotowireplayerid int `json:"RotoWirePlayerID,omitempty"`
	Depthorder int `json:"DepthOrder,omitempty"`
	Upcominggameweek int `json:"UpcomingGameWeek,omitempty"`
	Active bool `json:"Active,omitempty"`
	Usatodayheadshotnobackgroundurl string `json:"UsaTodayHeadshotNoBackgroundUrl,omitempty"`
	Fanduelname string `json:"FanDuelName,omitempty"`
	Number int `json:"Number,omitempty"`
	Sportsdirectplayerid int `json:"SportsDirectPlayerID,omitempty"`
	Currentteam string `json:"CurrentTeam,omitempty"`
	Declaredinactive bool `json:"DeclaredInactive,omitempty"`
	Xmlteamplayerid int `json:"XmlTeamPlayerID,omitempty"`
	Injurypractice string `json:"InjuryPractice,omitempty"`
	Shortname string `json:"ShortName,omitempty"`
	Byeweek int `json:"ByeWeek,omitempty"`
	Injurystartdate string `json:"InjuryStartDate,omitempty"`
	Draftkingsplayerid int `json:"DraftKingsPlayerID,omitempty"`
	Birthdatestring string `json:"BirthDateString,omitempty"`
}

// PlayerGameProjection represents the PlayerGameProjection schema from the OpenAPI specification
type PlayerGameProjection struct {
	Blockedkickreturnyards float64 `json:"BlockedKickReturnYards,omitempty"`
	Homeoraway string `json:"HomeOrAway,omitempty"`
	Miscfumblesrecovered float64 `json:"MiscFumblesRecovered,omitempty"`
	Puntreturnlong float64 `json:"PuntReturnLong,omitempty"`
	Playergameid int `json:"PlayerGameID,omitempty"`
	Passinglong float64 `json:"PassingLong,omitempty"`
	Fantasydraftposition string `json:"FantasyDraftPosition,omitempty"`
	Season int `json:"Season,omitempty"`
	Passingyards float64 `json:"PassingYards,omitempty"`
	Windspeed int `json:"WindSpeed,omitempty"`
	Tacklesforloss float64 `json:"TacklesForLoss,omitempty"`
	Offensivetouchdowns float64 `json:"OffensiveTouchdowns,omitempty"`
	Fieldgoalsmade40to49 float64 `json:"FieldGoalsMade40to49,omitempty"`
	Injurypracticedescription string `json:"InjuryPracticeDescription,omitempty"`
	Seasontype int `json:"SeasonType,omitempty"`
	Kickreturnfaircatches float64 `json:"KickReturnFairCatches,omitempty"`
	Passesdefended float64 `json:"PassesDefended,omitempty"`
	Fieldgoalreturntouchdowns float64 `json:"FieldGoalReturnTouchdowns,omitempty"`
	Draftkingsposition string `json:"DraftKingsPosition,omitempty"`
	Kickreturntouchdowns float64 `json:"KickReturnTouchdowns,omitempty"`
	Activated int `json:"Activated,omitempty"`
	Puntreturns float64 `json:"PuntReturns,omitempty"`
	Positioncategory string `json:"PositionCategory,omitempty"`
	Interceptionreturntouchdowns float64 `json:"InterceptionReturnTouchdowns,omitempty"`
	Humidity int `json:"Humidity,omitempty"`
	Fantasypointsfanduel float64 `json:"FantasyPointsFanDuel,omitempty"`
	Fieldgoalsmade50plus float64 `json:"FieldGoalsMade50Plus,omitempty"`
	Opponent string `json:"Opponent,omitempty"`
	Specialteamsassistedtackles float64 `json:"SpecialTeamsAssistedTackles,omitempty"`
	Twopointconversionreceptions float64 `json:"TwoPointConversionReceptions,omitempty"`
	Passingattempts float64 `json:"PassingAttempts,omitempty"`
	Injurynotes string `json:"InjuryNotes,omitempty"`
	Globalteamid int `json:"GlobalTeamID,omitempty"`
	Rushingyardsperattempt float64 `json:"RushingYardsPerAttempt,omitempty"`
	Fieldgoalslongestmade float64 `json:"FieldGoalsLongestMade,omitempty"`
	Fanduelposition string `json:"FanDuelPosition,omitempty"`
	Globalopponentid int `json:"GlobalOpponentID,omitempty"`
	Rushingattempts float64 `json:"RushingAttempts,omitempty"`
	Fieldgoalsattempted float64 `json:"FieldGoalsAttempted,omitempty"`
	Fumbleslost float64 `json:"FumblesLost,omitempty"`
	Defensiveteamsnaps int `json:"DefensiveTeamSnaps,omitempty"`
	Extrapointsattempted float64 `json:"ExtraPointsAttempted,omitempty"`
	Scoringdetails []ScoringDetail `json:"ScoringDetails,omitempty"`
	Played int `json:"Played,omitempty"`
	Snapcountsconfirmed bool `json:"SnapCountsConfirmed,omitempty"`
	Tackles float64 `json:"Tackles,omitempty"`
	Fieldgoalreturnyards float64 `json:"FieldGoalReturnYards,omitempty"`
	Solotackles float64 `json:"SoloTackles,omitempty"`
	Started int `json:"Started,omitempty"`
	Puntnetaverage float64 `json:"PuntNetAverage,omitempty"`
	Receivinglong float64 `json:"ReceivingLong,omitempty"`
	Safetiesallowed float64 `json:"SafetiesAllowed,omitempty"`
	Puntaverage float64 `json:"PuntAverage,omitempty"`
	Blockedkickreturntouchdowns float64 `json:"BlockedKickReturnTouchdowns,omitempty"`
	Teamid int `json:"TeamID,omitempty"`
	Passingsacks float64 `json:"PassingSacks,omitempty"`
	Passingyardsperattempt float64 `json:"PassingYardsPerAttempt,omitempty"`
	Puntnetyards float64 `json:"PuntNetYards,omitempty"`
	Quarterbackhits float64 `json:"QuarterbackHits,omitempty"`
	Fantasydraftsalary int `json:"FantasyDraftSalary,omitempty"`
	Kickreturns float64 `json:"KickReturns,omitempty"`
	Blockedkicks float64 `json:"BlockedKicks,omitempty"`
	Specialteamsteamsnaps int `json:"SpecialTeamsTeamSnaps,omitempty"`
	Twopointconversionpasses float64 `json:"TwoPointConversionPasses,omitempty"`
	Fantasydatasalary int `json:"FantasyDataSalary,omitempty"`
	Kickreturnyardsperattempt float64 `json:"KickReturnYardsPerAttempt,omitempty"`
	Interceptions float64 `json:"Interceptions,omitempty"`
	Twopointconversionruns float64 `json:"TwoPointConversionRuns,omitempty"`
	Fumblesownrecoveries float64 `json:"FumblesOwnRecoveries,omitempty"`
	Rushingtouchdowns float64 `json:"RushingTouchdowns,omitempty"`
	Playingsurface string `json:"PlayingSurface,omitempty"`
	Injurybodypart string `json:"InjuryBodyPart,omitempty"`
	Receivingtouchdowns float64 `json:"ReceivingTouchdowns,omitempty"`
	Number int `json:"Number,omitempty"`
	Miscsolotackles float64 `json:"MiscSoloTackles,omitempty"`
	Puntinside20 float64 `json:"PuntInside20,omitempty"`
	Fantasypointsfantasydraft float64 `json:"FantasyPointsFantasyDraft,omitempty"`
	Gamekey string `json:"GameKey,omitempty"`
	Miscassistedtackles float64 `json:"MiscAssistedTackles,omitempty"`
	Passingtouchdowns float64 `json:"PassingTouchdowns,omitempty"`
	Punts float64 `json:"Punts,omitempty"`
	Rushingyards float64 `json:"RushingYards,omitempty"`
	Fantasypointsppr float64 `json:"FantasyPointsPPR,omitempty"`
	Fumblesforced float64 `json:"FumblesForced,omitempty"`
	Name string `json:"Name,omitempty"`
	Sackyards float64 `json:"SackYards,omitempty"`
	Punttouchbacks float64 `json:"PuntTouchbacks,omitempty"`
	Passingyardspercompletion float64 `json:"PassingYardsPerCompletion,omitempty"`
	Interceptionreturnyards float64 `json:"InterceptionReturnYards,omitempty"`
	Defensivetouchdowns float64 `json:"DefensiveTouchdowns,omitempty"`
	Kickreturnlong float64 `json:"KickReturnLong,omitempty"`
	Gamedate string `json:"GameDate,omitempty"`
	Specialteamssolotackles float64 `json:"SpecialTeamsSoloTackles,omitempty"`
	Puntreturntouchdowns float64 `json:"PuntReturnTouchdowns,omitempty"`
	Fumblesrecovered float64 `json:"FumblesRecovered,omitempty"`
	Receivingyardsperreception float64 `json:"ReceivingYardsPerReception,omitempty"`
	Injurystatus string `json:"InjuryStatus,omitempty"`
	Victivsalary int `json:"VictivSalary,omitempty"`
	Receivingtargets float64 `json:"ReceivingTargets,omitempty"`
	Draftkingssalary int `json:"DraftKingsSalary,omitempty"`
	Fieldgoalshadblocked float64 `json:"FieldGoalsHadBlocked,omitempty"`
	Opponentpositionrank int `json:"OpponentPositionRank,omitempty"`
	Offensivesnapsplayed int `json:"OffensiveSnapsPlayed,omitempty"`
	Rushinglong float64 `json:"RushingLong,omitempty"`
	Kickreturnyards float64 `json:"KickReturnYards,omitempty"`
	Injurystartdate string `json:"InjuryStartDate,omitempty"`
	Passingcompletionpercentage float64 `json:"PassingCompletionPercentage,omitempty"`
	Puntreturnfaircatches float64 `json:"PuntReturnFairCatches,omitempty"`
	Assistedtackles float64 `json:"AssistedTackles,omitempty"`
	Passingsackyards float64 `json:"PassingSackYards,omitempty"`
	Team string `json:"Team,omitempty"`
	Puntreturnyardsperattempt float64 `json:"PuntReturnYardsPerAttempt,omitempty"`
	Specialteamsfumblesrecovered float64 `json:"SpecialTeamsFumblesRecovered,omitempty"`
	Twopointconversionreturns float64 `json:"TwoPointConversionReturns,omitempty"`
	Playerid int `json:"PlayerID,omitempty"`
	Opponentid int `json:"OpponentID,omitempty"`
	Passingcompletions float64 `json:"PassingCompletions,omitempty"`
	Fieldgoalsmade20to29 float64 `json:"FieldGoalsMade20to29,omitempty"`
	Opponentrank int `json:"OpponentRank,omitempty"`
	Specialteamsfumblesforced float64 `json:"SpecialTeamsFumblesForced,omitempty"`
	Receptions float64 `json:"Receptions,omitempty"`
	Declaredinactive bool `json:"DeclaredInactive,omitempty"`
	Puntlong float64 `json:"PuntLong,omitempty"`
	Receptionpercentage float64 `json:"ReceptionPercentage,omitempty"`
	Fumblereturntouchdowns float64 `json:"FumbleReturnTouchdowns,omitempty"`
	Puntreturnyards float64 `json:"PuntReturnYards,omitempty"`
	Sacks float64 `json:"Sacks,omitempty"`
	Yahoosalary int `json:"YahooSalary,omitempty"`
	Fantasypoints float64 `json:"FantasyPoints,omitempty"`
	Specialteamstouchdowns float64 `json:"SpecialTeamsTouchdowns,omitempty"`
	Receivingyards float64 `json:"ReceivingYards,omitempty"`
	Specialteamssnapsplayed int `json:"SpecialTeamsSnapsPlayed,omitempty"`
	Passingrating float64 `json:"PassingRating,omitempty"`
	Stadium string `json:"Stadium,omitempty"`
	Fanduelsalary int `json:"FanDuelSalary,omitempty"`
	Offensiveteamsnaps int `json:"OffensiveTeamSnaps,omitempty"`
	Day string `json:"Day,omitempty"`
	Puntyards float64 `json:"PuntYards,omitempty"`
	Safeties float64 `json:"Safeties,omitempty"`
	Fumblereturnyards float64 `json:"FumbleReturnYards,omitempty"`
	Fantasypointsdraftkings float64 `json:"FantasyPointsDraftKings,omitempty"`
	Temperature int `json:"Temperature,omitempty"`
	Fumblesoutofbounds float64 `json:"FumblesOutOfBounds,omitempty"`
	Miscfumblesforced float64 `json:"MiscFumblesForced,omitempty"`
	Isgameover bool `json:"IsGameOver,omitempty"`
	Fieldgoalsmade float64 `json:"FieldGoalsMade,omitempty"`
	Defensivesnapsplayed int `json:"DefensiveSnapsPlayed,omitempty"`
	Offensivefumblerecoverytouchdowns float64 `json:"OffensiveFumbleRecoveryTouchdowns,omitempty"`
	Puntshadblocked float64 `json:"PuntsHadBlocked,omitempty"`
	Touchdowns float64 `json:"Touchdowns,omitempty"`
	Passinginterceptions float64 `json:"PassingInterceptions,omitempty"`
	Fieldgoalsmade30to39 float64 `json:"FieldGoalsMade30to39,omitempty"`
	Position string `json:"Position,omitempty"`
	Week int `json:"Week,omitempty"`
	Yahooposition string `json:"YahooPosition,omitempty"`
	Receivingyardspertarget float64 `json:"ReceivingYardsPerTarget,omitempty"`
	Extrapointsmade float64 `json:"ExtraPointsMade,omitempty"`
	Datetime string `json:"DateTime,omitempty"`
	Fumbles float64 `json:"Fumbles,omitempty"`
	Injurypractice string `json:"InjuryPractice,omitempty"`
	Fantasyposition string `json:"FantasyPosition,omitempty"`
	Fantasypointsyahoo float64 `json:"FantasyPointsYahoo,omitempty"`
	Fieldgoalpercentage float64 `json:"FieldGoalPercentage,omitempty"`
	Scoreid int `json:"ScoreID,omitempty"`
	Extrapointshadblocked float64 `json:"ExtraPointsHadBlocked,omitempty"`
	Globalgameid int `json:"GlobalGameID,omitempty"`
	Shortname string `json:"ShortName,omitempty"`
	Fieldgoalsmade0to19 float64 `json:"FieldGoalsMade0to19,omitempty"`
}
